#!/usr/bin/env bash
# Jordan Justen : this file is public domain

FDO_SCRIPT=${BASH_SOURCE[0]}
source "$(cd "$(dirname "$(readlink -f "$FDO_SCRIPT")")" && pwd)"/menv

PROJECT=`basename $PWD`

: ${FDO=".."}

if [[ "$PROJECT" =~ ^mesa.*$ ]]; then
PROJECT=mesa
fi

if [[ -x $FDO/$PROJECT-config ]]; then
  $FDO/$PROJECT-config "$@"
elif [[ -x $HOME/src/fdo/$PROJECT-config ]]; then
  $HOME/src/fdo/$PROJECT-config "$@"
else
  echo Unknown project: $PROJECT
fi
