#!/bin/bash
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

PROJECT=`basename $PWD`

: ${FDO=".."}

if [[ "$PROJECT" =~ ^mesa.+$ ]]; then
PROJECT=mesa
fi

if [[ -x $FDO/$PROJECT-config ]]; then
  $FDO/$PROJECT-config "$@"
else
  echo Unknown project: $PROJECT
fi
