#!/usr/bin/env bash
# Jordan Justen : this file is public domain

BASE_DIR=$HOME/src/fdo
source $BASE_DIR/menv

export LD_LIBRARY_PATH=$BASE_DIR/glaze/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export FIPS_LIBGL=$BASE_DIR/mesa/lib/libGL.so
export GLAZE_LIBGL=$BASE_DIR/mesa/lib/libGL.so
export GLAZE_WRAPPER=$BASE_DIR/fips/libfips-64.so
export vblank_mode=0

$@
