#!/bin/bash

if [ ! -v DEBUG ]; then
  DEBUG=1
fi

if [[ -z "$MENV_INCLUDED" ]];
then

export MENV_INCLUDED=1


export FDO="$(cd ".." && pwd)"

if [[ "$FDO" =~ ^.*/fdo[^/]*$ ]]; then
    export FDO_PRJ="$(basename "$(pwd)")"
    if [[ "$FDO_PRJ" =~ ^mesa.*$ ]]; then MESA="$FDO_PRJ"; fi
else
    export FDO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    unset FDO_PRJ
fi

if [ "$(basename $FDO)" == "fdo32" ]; then
    export FDO_SIZE=32
    export LIB_ARCH=i386
else
    export FDO_SIZE=64
    export LIB_ARCH=x86_64
fi

: ${MESA="mesa"}
export MESA_DIR=$FDO/$MESA

FDO_BUILD_DIR=$FDO/build
if [ "$DEBUG" -ne 0 ]; then
    FDO_BUILD_DIR=$FDO_BUILD_DIR/debug
else
    FDO_BUILD_DIR=$FDO_BUILD_DIR/release
fi

mkdir -p "$FDO_BUILD_DIR"

if [ ! -v PREFIX ]; then
    export PREFIX="$FDO_BUILD_DIR/pfx"
fi

export MESA_BUILD_DIR="$FDO_BUILD_DIR/$MESA"

export VK_ICD_FILENAMES=$MESA_DIR/src/intel/vulkan/dev_icd.json
#export ACLOCAL="aclocal -I $PREFIX/share/aclocal"
export PKG_CONFIG_LIBDIR=$PREFIX/lib/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_LIBDIR:$PREFIX/share/pkgconfig:/usr/lib/pkgconfig:/usr/lib/$LIB_ARCH-linux-gnu/pkgconfig:/usr/share/pkgconfig
export LD_LIBRARY_PATH=$MESA_DIR/lib:$PREFIX/lib/$LIB_ARCH-linux-gnu:$PREFIX/lib:$PREFIX/lib/dri:/usr/lib:/usr/lib/$LIB_ARCH-linux-gnu
export LD_LIBRARY_PATH=$FDO/LoaderAndTools/loader:$LD_LIBRARY_PATH
export LIBRARY_PATH=$LD_LIBRARY_PATH
export LIBGL_DRIVERS_DIR=$PREFIX/lib/dri
export DRI_DRIVER_SEARCH_DIR=$LIBGL_DRIVERS_DIR
export EGL_DRIVERS_PATH=$LIBGL_DRIVERS_DIR
#export TRACE_LIBGL=$PREFIX/lib/libGL.so
export CMAKE_INCLUDE_PATH=$PREFIX/include
export CMAKE_LIBRARY_PATH=$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$PREFIX
export CMAKE_INSTALL_PREFIX=$PREFIX
export PATH=$PREFIX/bin:$PREFIX/sbin:$PATH
export CPATH=$CMAKE_INCLUDE_PATH

fi
