#!/bin/bash
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

if [ -z "$CFLAGS" ]; then
CFLAGS="-m${FDO_SIZE}"
fi
if [ -z "$CXXFLAGS" ]; then
CXXFLAGS="-m${FDO_SIZE}"
fi
if [ -z "$CPPFLAGS" ]; then
CPPFLAGS="-m${FDO_SIZE}"
fi

if [[ "$DEBUG" == "0" ]]; then
  unset DEBUG
fi

if [ -z "$DEBUG" ]; then
  D_CFLAGS='-O2 -DNDEBUG --debug'
  export CFLAGS="$CFLAGS $D_CFLAGS"
  export CXXFLAGS="$CXXFLAGS $D_CFLAGS"
  export CPPFLAGS="$CPPFLAGS $D_CFLAGS"
  MESON_BUILDTYPE=release
else
  export DEBUG_FLAG=--enable-debug
  MESON_BUILDTYPE=debug
fi

if [[ "$MESON" -ne 0 && ! -f "$MESA_DIR/meson.build" ]]; then
    MESON=0
fi

if [[ "$MESON" -ne 0 ]]; then
    meson \
        -Dgallium-omx=disabled -Dgallium-drivers= \
        -Ddri-drivers=i965 -Dvulkan-drivers=intel \
        -Dtools=intel -Dbuild-tests=true \
        --prefix="$PREFIX" \
        --buildtype $MESON_BUILDTYPE \
        "$MESA_DIR" "$MESA_BUILD_DIR"
else
./autogen.sh \
  --prefix=$PREFIX \
  --enable-gles3 --enable-gles2 --enable-gles1 \
  --enable-egl \
  --with-dri-drivers=i965,swrast \
  $DEBUG_FLAG \
  $HOST_FLAG \
  --enable-texture-float \
  --enable-shared-glapi \
  --enable-glx-tls \
  --with-egl-drivers=dri2,dri3,glx --with-egl-platforms=x11,drm,wayland \
  --enable-gbm \
  --disable-glu --with-gallium-drivers='' \
  --disable-gallium-egl \
  --with-vulkan-drivers=intel \
  CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" CPPFLAGS="$CPPFLAGS" \
  "$@"
fi

#  --with-egl-platforms=x11,wayland,drm --enable-gbm --disable-gallium-egl

: ${FDO_PRJ="mesa"}

FDO_NAME="$(basename "$FDO")"

if [ -n "$DEBUG" ]; then
  echo $FDO_NAME/$FDO_PRJ configured for DEBUG
else
  echo $FDO_NAME/$FDO_PRJ configured for RELEASE
fi

