#!/usr/bin/env bash
# Jordan Justen : this file is public domain

source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

if [[ -f "$MESA_BUILD_DIR/build.ninja" ]]; then
    NINJA=1
else
    NINJA=0
fi


if [[ "$NINJA" -ne 0 ]]; then
    nice -n 20 ninja -C "$MESA_BUILD_DIR" "$@" && \
        ninja -C "$MESA_BUILD_DIR" install
    NRESULT=$?
else
    cd "$MESA_BUILD_DIR" && \
        PATH=/usr/lib/ccache:$PATH make -j8 "$@" &&
        make -j8 install
    NRESULT=$?
fi


echo "Built $MESA_DIR => $NRESULT"

exit $NRESULT
