#!/bin/bash
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

if [[ "$MESON" -ne 0 && ! -f "$MESA_DIR/meson.build" ]]; then
    MESON=0
fi

if [[ "$MESON" -ne 0 ]]; then
    ninja -C "$MESA_BUILD_DIR" && \
        ninja -C "$MESA_BUILD_DIR" install
    NRESULT=$?
else
    cd "$MESA_BUILD_DIR" && \
        PATH=/usr/lib/ccache:$PATH make -j8 $* &&
        make -j8 install
    NRESULT=$?
fi


echo "Built $MESA_DIR => $NRESULT"

exit $NRESULT
