#!/usr/bin/env bash
# Jordan Justen : this file is public domain

source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

export PIGLIT_SOURCE_DIR=$FDO/piglit

if [[ -v OUT_OF_TREE && ("$OUT_OF_TREE" == "" || "$OUT_OF_TREE" == "1" || \
                         "$OUT_OF_TREE" == "true") ]]; then
    OUT_OF_TREE=1
else
    OUT_OF_TREE=0
fi

if [[ "$OUT_OF_TREE" -ne 0 ]]; then
    export PIGLIT_BUILD_DIR="$FDO_BUILD_DIR/piglit"
    if [[ -d "$PIGLIT_BUILD_DIR" && ! -z "$PIGLIT_BUILD_DIR" ]]; then
        echo "Removing old piglit build dir: $PIGLIT_BUILD_DIR"
        rm -r "$PIGLIT_BUILD_DIR"
    fi

    if [[ ! -d "$PIGLIT_BUILD_DIR" && ! -z "$PIGLIT_BUILD_DIR" ]]; then
        mkdir -p "$PIGLIT_BUILD_DIR"
    fi
else
    export PIGLIT_BUILD_DIR="$PIGLIT_SOURCE_DIR"
fi

cd "$PIGLIT_BUILD_DIR"
cmake \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DPIGLIT_BUILD_GLES1_TESTS=1 -DPIGLIT_BUILD_GLES2_TESTS=1 \
  -DPIGLIT_BUILD_GLES3_TESTS=1 \
  -DPIGLIT_USE_WAFFLE=1 \
  -G Ninja \
  $PIGLIT_SOURCE_DIR \
  "$@"

#  -DBUILD_GLES1_TESTS=1 -DBUILD_GLES2_TESTS=1 \
#  -DUSE_WAFFLE=1 \

echo "$PIGLIT_BUILD_DIR configured"
