#!/bin/bash
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"/menv

export PIGLIT_BUILD_DIR="$FDO_BUILD_DIR/piglit"
export PIGLIT_SOURCE_DIR=$FDO/piglit

if [[ -d "$PIGLIT_BUILD_DIR" && ! -z "$PIGLIT_BUILD_DIR" ]]; then
    echo "Removing old piglit build dir: $PIGLIT_BUILD_DIR"
    rm -r "$PIGLIT_BUILD_DIR"
fi

if [[ ! -d "$PIGLIT_BUILD_DIR" && ! -z "$PIGLIT_BUILD_DIR" ]]; then
    mkdir -p "$PIGLIT_BUILD_DIR"
fi

cd "$PIGLIT_BUILD_DIR"
cmake \
  -DCMAKE_LIBRARY_PATH=$(echo $LIBRARY_PATH | sed 's/:/;/g') \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DPIGLIT_BUILD_GLES1_TESTS=1 -DPIGLIT_BUILD_GLES2_TESTS=1 \
  -DPIGLIT_BUILD_GLES3_TESTS=1 \
  -DPIGLIT_USE_WAFFLE=1 \
  -G Ninja \
  $PIGLIT_SOURCE_DIR

#  -DBUILD_GLES1_TESTS=1 -DBUILD_GLES2_TESTS=1 \
#  -DUSE_WAFFLE=1 \

echo "$PIGLIT_BUILD_DIR configured"
