#!/bin/bash
# Jordan Justen : this file is public domain

HERE="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

set -e

if [[ $# < 1 ]]; then
    unset WHAT
else
    WHAT="$1"
    shift
fi

case "$WHAT" in
    1k)
        TEST_LIST="--test-list=$HOME/src/fdo/test-lists/piglit-gen12-simics.txt"
        PROFILE=all
        ;;
    gpu|sanity|all)
        TEST_LIST=""
        PROFILE="$WHAT"
        ;;
    vk-rt)
        TEST_LIST="-t "'dEQP-VK.ray_tracing_pipeline.builtin.launchidext.*_1_1_1'
        TEST_LIST="--test-list=$HOME/src/fdo/piglit/vkcts-rt-tests.txt"
        PROFILE="deqp_vk"
        ;;
    *)
        WHAT=""
        ;;
esac

if [ -z "$WHAT" ]; then
    echo "Usage: $0 [1k | all | gpu | sanity] [piglit params...]"
    exit -1
fi

if [ -x "$HERE/piglit/piglit" ]; then
    PIGLIT="$HERE/piglit"
else
    PIGLIT="$HOME/src/fdo/piglit"
fi
BIN="$PIGLIT/piglit"

if [ ! -x "$BIN" ]; then
    echo "$BIN is not executable"
    exit 1
fi

export vblank_mode=0
export NIR_VALIDATE=0
unset DISPLAY

TIMENOW=`date +%y%m%d-%H%M%S`
: ${RESULTS_SUBDIR=`hostname`}
LOG_DIR="$HERE/results/$RESULTS_SUBDIR"
mkdir -p "$LOG_DIR"
LOG=$LOG_DIR/$WHAT-$TIMENOW

# Required
: ${CMD_ENV="$HERE/run-with-dev-mesa"}
CMD="$BIN run $PROFILE"
if [ -n "$TEST_LIST" ]; then
    CMD="$CMD $TEST_LIST"
fi
CMD="$CMD $LOG"

cd $PIGLIT
echo $CMD "$@"
time nice $CMD_ENV $CMD "$@"
